title: Iterum
description: Devblog about our games.
author: Kaic & Marcelo
github: https://github.com/IterumCorp
about: Devblog about our games.
disqus_shortname: iterum
google_analytics: UA-80289341-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      text: Github
      link: "https://github.com/IterumCorp"
    - icon: fa-twitter
      text: Twitter
      link: "#"
    - icon: fa-youtube
      text: YouTube
      link: "#"

share:
  twitter_username:
  fb_appid:

urls:
    - icon: fa-home
      text: Home
      url: /
    - icon: fa-users
      text: About Us
      url: /about/
    - icon: fa-archive
      text: Projects
      url: /projects/
    - icon: fa-rss
      text: XML Feed
      url: /feed.xml

url: "https://iterumcorp.github.io"
baseurl: ""
paginate: 5
per_page: 5
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
