title: Iterum
description: Devblog sobre nossos jogos.
author: Kaic & Marcelo
github: https://github.com/IterumCorp
about: Devblog sobre nossos jogos.
disqus_shortname: iterum
google_analytics: UA-80289341-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      text: Github
      link: "https://github.com/IterumCorp"
    - icon: fa-twitter
      text: Twitter
      link: "https://twitter.com/tck_aic"
    - icon: fa-youtube
      text: YouTube
      link: "https://www.youtube.com/channel/UChJzR70zvKDiiqO6MMBGLiw"

share:
  twitter_username:
  fb_appid:

urls:
    - icon: fa-home
      text: Inicio
      url: /
    - icon: fa-users
      text: Sobre
      url: /sobre/
    - icon: fa-archive
      text: Projetos
      url: /projetos/
    - icon: fa-rss
      text: XML Feed
      url: /feed.xml

url: "http://iterum.info"
baseurl: ""
paginate: 5
per_page: 5
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
