title: 01MK
description: Maka devblog
author: Kaic Bastidas & Marcelo da Silva
github: https://github.com/01mk
about: Wannabe game makers.
disqus_shortname: 01mk
google_analytics: UA-80289341-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      text: Github
      link: "https://github.com/01mk"
    - icon: fa-twitter
      text: Twitter
      link: "#"
    - icon: fa-youtube
      text: YouTube
      link: "#"

share:
  twitter_username:
  fb_appid:

urls:
    - icon: fa-home
      text: Home
      url: /
    - icon: fa-users
      text: About Me
      url: /about/
    - icon: fa-archive
      text: Projects
      url: /projects/
    - icon: fa-file-code-o
      text: XML Feed
      url: /feed.xml

url: "https://01mk.github.io"
baseurl: ""
paginate: 5
per_page: 5
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
